sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=sql:S1192
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.sql
sonar.issue.ignore.multicriteria.e2.ruleKey=plsql:S1192
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.sql
